version: '3.9'
name: local-archive
services:
  api:
    build: ./src/api
    container_name: api
    ports:
      - "5002:8080"
    volumes:
      - ./src/api:/app
    environment:
      - UVICORN_HOST=0.0.0.0
      - APP_ENVIRONMENT=Development
    depends_on:
      - db
    restart: always

  webapp:
    build: ./src/web
    container_name: webapp
    ports:
      - "5001:8080"
    depends_on:
      - api
    restart: always

  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  tests:
    build:
      context: .
      dockerfile: tests/Dockerfile
    container_name: tests
    depends_on:
      - db
      - api
    volumes:
      - ./tests:/tests
      - ./src:/app
      - ./src/api/requirements.txt:/tests/requirements.txt

    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
    working_dir: /tests
    command: ["pytest"]
    profiles:
      - tests



volumes:
  postgres_data:
