version: '3.9'
name: local-archive
include:
  - docker-compose.deps.yml
services:
  api:
    build: ./api
    container_name: api
    ports:
      - "5002:8080"
    environment:
      - UVICORN_HOST=0.0.0.0
      - APP_ENVIRONMENT=Development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydatabase
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - db
      - elasticsearch
    restart: always

  webapp:
    build: ./web
    container_name: webapp
    ports:
      - "5001:8080"
    depends_on:
      - api
    restart: always