name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.build_push.outputs.image }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: '${{ vars.GCP_PROJECT }}'
          install_components: 'beta'

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ vars.GCP_REGION }}-docker.pkg.dev --quiet

      - name: Build and Push Docker Image
        id: build_push
        run: |
          IMAGE_TAG="${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT }}/default/webapp:${{ github.sha }}"
          docker build -t $IMAGE_TAG ./src/web
          docker push $IMAGE_TAG
          echo "image=$IMAGE_TAG" >> $GITHUB_OUTPUT

  deploy:
    name: Deploy to Cloud Run
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: local-archive
          install_components: 'beta'

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy webapp \
            --image="${{ needs.build.outputs.image }}" \
            --region=${{ vars.GCP_PROJECT }} \
            --platform=managed \
            --allow-unauthenticated \
            --quiet